//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultItemProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationPerformed
    {
        public int ID { get; set; }
        public int qtyDone { get; set; }
        public System.DateTime timePerformed { get; set; }
        public string Notes { get; set; }
        public Nullable<int> usr_UserID { get; set; }
        public Nullable<int> OrderItemOperation_ID { get; set; }
    
        public virtual OrderItemOperation OrderItemOperation { get; set; }
        public virtual User User { get; set; }
    }
}
