//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultItemProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderItem()
        {
            this.NestedParts = new HashSet<NestedPart>();
            this.Nests = new HashSet<Nest>();
        }
    
        public int ID { get; set; }
        public int OrderID { get; set; }
        public bool IsComplete { get; set; }
        public int QtyRequired { get; set; }
        public int QtyNested { get; set; }
        public bool IsInProject { get; set; }
        public string Notes { get; set; }
        public int PartID { get; set; }
        public int RadanIDNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NestedPart> NestedParts { get; set; }
        public virtual Order Order { get; set; }
        public virtual Part Part { get; set; }
        public virtual RadanID RadanID { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nest> Nests { get; set; }
    }
}
