//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultItemProcessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadanID
    {
        public int ID { get; set; }
        public int RadanIDNumber { get; set; }
        public int OrderItemID { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
    }
}
