// <auto-generated />
using System;
using HorstMFG.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HorstMFG.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330110604_AddNestingStationIdToItems")]
    partial class AddNestingStationIdToItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HorstMFG.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImportedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("LocalPdfFolder")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<bool>("ReadyForProduction")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ImportedByUserId");

                    b.HasIndex("PlantId");

                    b.ToTable("batches", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.BatchItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInRadanProject")
                        .HasColumnType("boolean");

                    b.Property<int>("NestBatchId")
                        .HasColumnType("integer");

                    b.Property<int?>("NestingStationId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<int>("QtyNested")
                        .HasColumnType("integer");

                    b.Property<int>("QtyRequired")
                        .HasColumnType("integer");

                    b.Property<int?>("RadanIdNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NestBatchId");

                    b.HasIndex("NestingStationId");

                    b.HasIndex("PartId");

                    b.ToTable("batch_items", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.BatchProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Qty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("qty");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("batch_products", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.Nest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NestPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("nests", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.NestBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("PlantId");

                    b.ToTable("nest_batches", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.NestOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleOrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.HasIndex("ScheduleOrderId");

                    b.ToTable("nest_orders", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.NestedPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatchItemId")
                        .HasColumnType("integer");

                    b.Property<int>("NestId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrderItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchItemId");

                    b.HasIndex("NestId");

                    b.HasIndex("OrderItemId");

                    b.ToTable("nested_parts", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.NestingStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BridgeLastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BridgeVersion")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectName")
                        .HasColumnType("text");

                    b.Property<string>("ProjectPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("nesting_stations", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInRadanProject")
                        .HasColumnType("boolean");

                    b.Property<int>("NestOrderId")
                        .HasColumnType("integer");

                    b.Property<int?>("NestingStationId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<int>("QtyNested")
                        .HasColumnType("integer");

                    b.Property<int>("QtyRequired")
                        .HasColumnType("integer");

                    b.Property<int?>("RadanIdNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NestOrderId");

                    b.HasIndex("NestingStationId");

                    b.HasIndex("PartId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("HasBends")
                        .HasColumnType("boolean");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Thickness")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("parts", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.PartLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatchProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("HasPdf")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStock")
                        .HasColumnType("boolean");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Operations")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresPdf")
                        .HasColumnType("boolean");

                    b.Property<int?>("ScheduleOrderId")
                        .HasColumnType("integer");

                    b.Property<string>("StructCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Thickness")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("BatchProductId");

                    b.HasIndex("ScheduleOrderId");

                    b.ToTable("part_line_items", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("plants", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImportedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("LocalPdfFolder")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<bool>("ReadyForProduction")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ImportedByUserId");

                    b.HasIndex("PlantId");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.ScheduleOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Qty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("qty");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("schedule_orders", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.SystemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("system_configuration", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RoleName")
                        .IsUnique();

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.ApplicationUser", b =>
                {
                    b.HasOne("HorstMFG.Core.Entities.Plant", "Plant")
                        .WithMany("Users")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.Batch", b =>
                {
                    b.HasOne("HorstMFG.Core.Entities.ApplicationUser", "ImportedByUser")
                        .WithMany()
                        .HasForeignKey("ImportedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorstMFG.Core.Entities.Plant", "Plant")
                        .WithMany("Batches")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedByUser");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.BatchItem", b =>
                {
                    b.HasOne("HorstMFG.Core.Entities.NestBatch", "NestBatch")
                        .WithMany("Items")
                        .HasForeignKey("NestBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorstMFG.Core.Entities.NestingStation", "NestingStation")
                        .WithMany()
                        .HasForeignKey("NestingStationId");

                    b.HasOne("HorstMFG.Core.Entities.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NestBatch");

                    b.Navigation("NestingStation");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.BatchProduct", b =>
                {
                    b.HasOne("HorstMFG.Core.Entities.Batch", "Batch")
                        .WithMany("BatchProducts")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.Nest", b =>
                {
                    b.HasOne("HorstMFG.Core.Entities.Plant", "Plant")
                        .WithMany("Nests")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.NestBatch", b =>
                {
                    b.HasOne("HorstMFG.Core.Entities.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorstMFG.Core.Entities.Plant", "Plant")
                        .WithMany("NestBatches")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.NestOrder", b =>
                {
                    b.HasOne("HorstMFG.Core.Entities.Plant", "Plant")
                        .WithMany("NestOrders")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorstMFG.Core.Entities.ScheduleOrder", "ScheduleOrder")
                        .WithMany()
                        .HasForeignKey("ScheduleOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("ScheduleOrder");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.NestedPart", b =>
                {
                    b.HasOne("HorstMFG.Core.Entities.BatchItem", "BatchItem")
                        .WithMany("NestedParts")
                        .HasForeignKey("BatchItemId");

                    b.HasOne("HorstMFG.Core.Entities.Nest", "Nest")
                        .WithMany("NestedParts")
                        .HasForeignKey("NestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorstMFG.Core.Entities.OrderItem", "OrderItem")
                        .WithMany("NestedParts")
                        .HasForeignKey("OrderItemId");

                    b.Navigation("BatchItem");

                    b.Navigation("Nest");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.NestingStation", b =>
                {
                    b.HasOne("HorstMFG.Core.Entities.Plant", "Plant")
                        .WithMany("NestingStations")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("HorstMFG.Core.Entities.NestOrder", "NestOrder")
                        .WithMany("Items")
                        .HasForeignKey("NestOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorstMFG.Core.Entities.NestingStation", "NestingStation")
                        .WithMany()
                        .HasForeignKey("NestingStationId");

                    b.HasOne("HorstMFG.Core.Entities.Part", "Part")
                        .WithMany("OrderItems")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NestOrder");

                    b.Navigation("NestingStation");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.PartLineItem", b =>
                {
                    b.HasOne("HorstMFG.Core.Entities.BatchProduct", "BatchProduct")
                        .WithMany("Parts")
                        .HasForeignKey("BatchProductId");

                    b.HasOne("HorstMFG.Core.Entities.ScheduleOrder", "ScheduleOrder")
                        .WithMany("Parts")
                        .HasForeignKey("ScheduleOrderId");

                    b.Navigation("BatchProduct");

                    b.Navigation("ScheduleOrder");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.Schedule", b =>
                {
                    b.HasOne("HorstMFG.Core.Entities.ApplicationUser", "ImportedByUser")
                        .WithMany()
                        .HasForeignKey("ImportedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorstMFG.Core.Entities.Plant", "Plant")
                        .WithMany("Schedules")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedByUser");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.ScheduleOrder", b =>
                {
                    b.HasOne("HorstMFG.Core.Entities.Schedule", "Schedule")
                        .WithMany("ScheduleOrders")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.UserRole", b =>
                {
                    b.HasOne("HorstMFG.Core.Entities.ApplicationUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.Batch", b =>
                {
                    b.Navigation("BatchProducts");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.BatchItem", b =>
                {
                    b.Navigation("NestedParts");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.BatchProduct", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.Nest", b =>
                {
                    b.Navigation("NestedParts");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.NestBatch", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.NestOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.OrderItem", b =>
                {
                    b.Navigation("NestedParts");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.Part", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.Plant", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("NestBatches");

                    b.Navigation("NestOrders");

                    b.Navigation("NestingStations");

                    b.Navigation("Nests");

                    b.Navigation("Schedules");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.Schedule", b =>
                {
                    b.Navigation("ScheduleOrders");
                });

            modelBuilder.Entity("HorstMFG.Core.Entities.ScheduleOrder", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
