using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace ItemExport
{
    public partial class HorstMFGExport : Form
    {
        public HorstMFGExport()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //ItemExport.HorstMFGEntities dbContext = new ItemExport.HorstMFGEntities();
            // Call the Load method to get the data for the given DbSet from the database.
            //dbContext.Products.Load();
            // This line of code is generated by Data Source Configuration Wizard
            //gridControl1.DataSource = dbContext.Products.Local.ToBindingList();
        }

        public HorstMFGExport(List <Product> productList)
        {
            DataSet ds = new DataSet();
            
            gridView1.Columns.Clear();
            gridControl1.DataSource = null;
            gridControl1.DataSource = productList;

        }
    }
}
