//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemExport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HorstMFGEntities : DbContext
    {
        public HorstMFGEntities()
        : base("name=HorstMFGEntities")
        //: base("connectionString = provider=System.Data.SqlClient;provider connection string=data source=(localdb)\\MSSQLLocalDB;attachdbfilename=C:\\Users\\lorne\\source\repos\\HorstMFG\\HorstMFG\\App_Data\\HorstMFG.mdf;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework\" providerName = \"System.Data.EntityClient")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductProduct> ProductProducts { get; set; }
    }
}
